import: definition.yaml

concurrency:
  task:
    os-std: 5
  agent:
    # gpt-3.5-turbo-0613: 10
    gpt-4-1106-preview: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      # - gpt-3.5-turbo-0613
      - gpt-4-1106-preview
    task:
      - os-std

output: "outputs/{TIMESTAMP}"
