import: definition.yaml

concurrency:
  task:
    os-std: 5
  agent:
    # gpt-3.5-turbo-0125: 5
    gpt-4-0125-preview: 5

assignments: # List[Assignment] | Assignment
  - agent: # "task": List[str] | str ,  "agent": List[str] | str
      # - gpt-3.5-turbo-0125
      - gpt-4-0125-preview
    task:
      - os-std

output: "outputs/{TIMESTAMP}"
